"""Convert a Cosserat-rod plant JSON into FEM-compatible OBJ meshes.

Produces:
  - plant_branches.obj  — watertight mesh suitable for PhysX FEM tetrahedralization
  - plant_fruits.obj    — sphere meshes for every fruit node (visual only)
  - plant_metadata.json — fruit positions, bounding box, etc.

The watertight mesh is generated by:
  1. Creating trimesh capsules for every branch segment
  2. Thickening radii to a minimum for FEM stability
  3. Voxelizing the combined capsules at controllable resolution
  4. Extracting a watertight isosurface via marching cubes

This solves the non-manifold geometry (T-junctions at branch forks) and
degenerate triangle problems that crash PhysX's FEM tetrahedralizer.

Usage:
    python generate_plant_mesh.py --input <plant.json> [--output-dir <dir>]
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path

import numpy as np
import trimesh


# ---------------------------------------------------------------------------
# FEM mesh parameters
# ---------------------------------------------------------------------------
MIN_BRANCH_RADIUS = 0.008  # 8 mm — minimum branch thickness for FEM visibility
VOXEL_PITCH = 0.005        # 5 mm — balanced voxels: watertight + FEM-friendly


# ---------------------------------------------------------------------------
# Mesh-generation helpers
# ---------------------------------------------------------------------------

def _rotation_z_to(direction: np.ndarray) -> np.ndarray:
    """Return a 3x3 rotation matrix that rotates Z-axis onto *direction*."""
    d = direction / (np.linalg.norm(direction) + 1e-12)
    z = np.array([0.0, 0.0, 1.0])
    v = np.cross(z, d)
    c = np.dot(z, d)
    if np.linalg.norm(v) < 1e-8:
        return np.eye(3) if c > 0 else np.diag([1.0, -1.0, -1.0])
    vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + vx + vx @ vx / (1 + c)


def create_branch_capsule(p0: np.ndarray, p1: np.ndarray,
                          radius: float) -> trimesh.Trimesh | None:
    """Create a watertight capsule mesh for a single branch segment."""
    direction = p1 - p0
    length = float(np.linalg.norm(direction))
    if length < 1e-6:
        return None

    # Create capsule along Z axis, centered at origin
    capsule = trimesh.creation.capsule(height=length, radius=radius, count=[4, 8])

    # Build 4x4 transform: rotate Z→direction, translate to midpoint
    R = _rotation_z_to(direction)
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = (p0 + p1) / 2.0
    capsule.apply_transform(T)
    return capsule


def generate_sphere(center: np.ndarray, radius: float,
                    n_lat: int = 8, n_lon: int = 16) -> tuple[np.ndarray, np.ndarray]:
    """Return (vertices, faces) for a UV-sphere."""
    verts = []
    verts.append(center + np.array([0, 0, radius]))
    for i in range(1, n_lat):
        theta = math.pi * i / n_lat
        z = radius * math.cos(theta)
        r = radius * math.sin(theta)
        for j in range(n_lon):
            phi = 2 * math.pi * j / n_lon
            verts.append(center + np.array([r * math.cos(phi), r * math.sin(phi), z]))
    verts.append(center + np.array([0, 0, -radius]))
    verts = np.array(verts)

    faces = []
    for j in range(n_lon):
        j_next = (j + 1) % n_lon
        faces.append([0, 1 + j, 1 + j_next])
    for i in range(n_lat - 2):
        for j in range(n_lon):
            j_next = (j + 1) % n_lon
            curr = 1 + i * n_lon + j
            next_row = 1 + (i + 1) * n_lon + j
            curr_next = 1 + i * n_lon + j_next
            next_row_next = 1 + (i + 1) * n_lon + j_next
            faces.append([curr, next_row, next_row_next])
            faces.append([curr, next_row_next, curr_next])
    bottom_idx = len(verts) - 1
    last_ring_start = 1 + (n_lat - 2) * n_lon
    for j in range(n_lon):
        j_next = (j + 1) % n_lon
        faces.append([bottom_idx, last_ring_start + j_next, last_ring_start + j])
    return verts, np.array(faces, dtype=int)


def write_obj(filepath: str, verts: np.ndarray, faces: np.ndarray):
    """Write vertices and 0-indexed faces to a Wavefront OBJ file."""
    with open(filepath, "w") as f:
        f.write(f"# Generated plant mesh — {len(verts)} vertices, {len(faces)} faces\n")
        for v in verts:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")


# ---------------------------------------------------------------------------
# Main conversion
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert plant JSON to FEM-compatible OBJ meshes for Isaac Sim."
    )
    parser.add_argument("--input", type=str,
                        default=str(Path(__file__).resolve().parents[4]
                                    / "Plant_Robot_Interaction-master" / "data" / "plant" / "fruit-001.json"),
                        help="Path to the plant JSON file.")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory (defaults to same dir as this script).")
    parser.add_argument("--table-height", type=float, default=0.7,
                        help="Height of the table/pedestal — plant is shifted up by this amount.")
    parser.add_argument("--min-radius", type=float, default=MIN_BRANCH_RADIUS,
                        help="Minimum branch radius for FEM stability (metres).")
    parser.add_argument("--voxel-pitch", type=float, default=VOXEL_PITCH,
                        help="Voxel resolution for marching cubes (metres).")
    args = parser.parse_args()

    output_dir = args.output_dir or str(Path(__file__).resolve().parent)

    # Load plant data
    with open(args.input, "r") as f:
        plant = json.load(f)

    positions = np.array(plant["positions"])       # (N, 3)
    fathers = np.array(plant["fathers"])            # (N,)
    radii = np.array(plant["radii"])                # (N,)
    fruit_radii = np.array(plant["fruit_radii"])    # (N,)

    n_nodes = len(positions)
    print(f"[INFO] Loaded plant with {n_nodes} nodes")

    # Shift plant up by table height so it sits on a pedestal
    positions[:, 2] += args.table_height

    # ------------------------------------------------------------------
    # Build watertight branch mesh via voxelization + marching cubes
    # ------------------------------------------------------------------
    print(f"[INFO] Building capsules for branch segments (min_radius={args.min_radius*1000:.1f}mm)...")
    capsules = []
    for i in range(n_nodes):
        parent = fathers[i]
        if parent < 0:
            continue  # root node
        if fruit_radii[i] > 0:
            continue  # fruit node — handled separately

        p0 = positions[parent]
        p1 = positions[i]
        # Use the larger of the two radii, clamped to minimum
        r = max(max(radii[parent], radii[i]), args.min_radius)

        cap = create_branch_capsule(p0, p1, r)
        if cap is not None:
            capsules.append(cap)

    print(f"[INFO] Created {len(capsules)} capsules")

    if not capsules:
        print("[ERROR] No branch capsules created — check input data.")
        return

    # Concatenate all capsules into one mesh (non-manifold at overlaps)
    combined = trimesh.util.concatenate(capsules)
    print(f"[INFO] Combined mesh: {len(combined.vertices)} verts, {len(combined.faces)} faces")
    print(f"[INFO] Combined watertight: {combined.is_watertight}")

    # Voxelize → fill internal voids → marching cubes = watertight
    print(f"[INFO] Voxelizing at {args.voxel_pitch*1000:.1f}mm pitch...")
    voxels = combined.voxelized(pitch=args.voxel_pitch).fill()
    print(f"[INFO] Voxel grid shape: {voxels.matrix.shape}, "
          f"filled voxels: {voxels.matrix.sum()}")

    watertight = voxels.marching_cubes
    print(f"[INFO] Marching cubes: {len(watertight.vertices)} verts, "
          f"{len(watertight.faces)} faces, "
          f"watertight: {watertight.is_watertight}")

    branch_path = os.path.join(output_dir, "plant_branches.obj")
    watertight.export(branch_path)
    print(f"[INFO] Wrote branch mesh: {branch_path}")

    # ------------------------------------------------------------------
    # Build fruit meshes (visual only — physics handled by kinematic spheres)
    # ------------------------------------------------------------------
    fruit_indices = np.where(fruit_radii > 0)[0]
    print(f"[INFO] Found {len(fruit_indices)} fruit nodes: {fruit_indices.tolist()}")

    all_fruit_verts = []
    all_fruit_faces = []
    vert_offset = 0
    fruit_centers = []

    for idx in fruit_indices:
        center = positions[idx]
        radius = fruit_radii[idx]
        fruit_centers.append(center.tolist())

        verts, faces = generate_sphere(center, radius, n_lat=8, n_lon=16)
        all_fruit_verts.append(verts)
        all_fruit_faces.append(faces + vert_offset)
        vert_offset += len(verts)

    fruit_verts = np.vstack(all_fruit_verts)
    fruit_faces = np.vstack(all_fruit_faces)

    fruits_path = os.path.join(output_dir, "plant_fruits.obj")
    write_obj(fruits_path, fruit_verts, fruit_faces)
    print(f"[INFO] Wrote fruit mesh: {fruits_path}  ({len(fruit_verts)} verts, {len(fruit_faces)} faces)")

    # Individual fruit OBJs
    for i, idx in enumerate(fruit_indices):
        center = positions[idx]
        radius = fruit_radii[idx]
        verts, faces = generate_sphere(center, radius, n_lat=8, n_lon=16)
        path = os.path.join(output_dir, f"fruit_{i:02d}.obj")
        write_obj(path, verts, faces)
    print(f"[INFO] Wrote {len(fruit_indices)} individual fruit OBJ files")

    # ------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------
    metadata = {
        "n_nodes": n_nodes,
        "n_fruits": len(fruit_indices),
        "fruit_indices": fruit_indices.tolist(),
        "fruit_centers": fruit_centers,
        "fruit_radius": float(fruit_radii[fruit_indices[0]]),
        "table_height": args.table_height,
        "plant_bbox_min": positions.min(axis=0).tolist(),
        "plant_bbox_max": positions.max(axis=0).tolist(),
        "mesh_watertight": bool(watertight.is_watertight),
        "mesh_verts": len(watertight.vertices),
        "mesh_faces": len(watertight.faces),
        "min_branch_radius": args.min_radius,
        "voxel_pitch": args.voxel_pitch,
    }
    meta_path = os.path.join(output_dir, "plant_metadata.json")
    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"[INFO] Wrote metadata: {meta_path}")
    print("[DONE] FEM-compatible mesh generation complete.")


if __name__ == "__main__":
    main()
